import express from "express";
import bcrypt from "bcrypt";
import { getRepositories } from "../repositories/index.js";
import { authenticatedUser, safeUser } from "../lib/request-auth.js";
import { createTokens } from "../lib/auth-tokens.js";
export const router = express.Router();
export const generateAccessAndRefreshToken = async (userId) => { const users = getRepositories().users; const user = await users.findById(userId); if (!user) throw new Error("User not found"); const tokens = createTokens(user); await users.updateRefreshToken(userId, tokens.refreshToken); return tokens; };
router.post("/", async (req, res) => { try { const admin = await authenticatedUser(req); if (!admin) return res.status(401).json({ success: false, message: "Unauthorized: No token" }); if (admin.role !== "admin") return res.status(403).json({ success: false, message: "Only admins can register users" }); const { name, ID, password, type, role, parent = "", phone = "" } = req.body; if (!name || !ID || !password || !type || !role) return res.status(400).json({ success: false, message: "All fields are required" }); const users = getRepositories().users; const institutionId = String(ID).trim().toLowerCase(); if (await users.findByInstitutionId(institutionId)) return res.status(409).json({ success: false, message: "User already exists" }); const user = await users.create({ name, institutionId, passwordHash: await bcrypt.hash(password, 10), role, type, parentId: type === "student" ? parent : undefined, phone: ["doctor", "parent"].includes(type) && phone ? String(phone).trim() : undefined }); const { accessToken } = await generateAccessAndRefreshToken(user._id); return res.status(201).json({ success: true, message: "User created successfully", data: { user: safeUser(user), accessToken } }); } catch (error) { console.error("Register failed:", error instanceof Error ? error.message : "Unknown error"); return res.status(500).json({ success: false, message: "Server error" }); } });
export default router;
